name: CustomMusicDiscs
version: 1.1.2
main: me.roan.custommusicdiscs.CustomMusicDiscsPlugin
api-version: '1.21'
authors: [Roan]
commands:
  customdisc:
    description: Creates custom discs and applies the generated pack.
    usage: /customdisc create <name> <url.ogg> <color> | /customdisc pack
    permission: customdisc.use
permissions:
  customdisc.use:
    description: Allows creating custom discs and applying generated pack
    default: op
